### ISSUE TITLE
tar: graylog_0: file changed as we read it

### ISSUE THREAD

**Issue by tivrobo** [NDrive/graylog-archiver#2]
Hi again!

I have problem when trying to archive my very first index `graylog_0`, graylog-archiver exit with tar error:

```
2017-06-08 06:24:16,514 [INFO] Indices: ['graylog_43', 'graylog_19', 'graylog_45', 'graylog_18', 'graylog_26', 'graylog_23', 'graylog_33', 'graylog_28', 'graylog_22', 'graylog_25', 'graylog_35', 'graylog_2', 'graylog_32', 'graylog_7', 'graylog_40', 'graylog_39', 'graylog_6', 'graylog_37', 'graylog_41', 'graylog_20', 'graylog_1', 'graylog_4', 'graylog_11', 'graylog_8', 'graylog_10', 'graylog_21', 'graylog_29', 'graylog_9', 'graylog_13', 'graylog_27', 'graylog_5', 'graylog_34', 'graylog_24', 'graylog_16', 'graylog_44', 'graylog_31', 'graylog_15', 'graylog_46', 'graylog_0', 'graylog_3', 'graylog_36', 'graylog_12', 'graylog_42', 'graylog_14', 'graylog_17', 'graylog_38', 'graylog_30']
2017-06-08 06:24:16,519 [INFO] Archiving ['graylog_0']
2017-06-08 06:24:16,519 [INFO] Archiving graylog_0...
2017-06-08 06:24:16,519 [INFO] Dumping from elasticsearch...
2017-06-08 06:24:19,592 [INFO] Compressing directory...
Traceback (most recent call last):
  File "/usr/local/bin/graylog-archiver", line 9, in <module>
    load_entry_point('graylog-archiver==0.1.3', 'console_scripts', 'graylog-archiver')()
  File "/usr/local/lib/python3.4/dist-packages/graylog_archiver/cli.py", line 33, in main
    archiver.archive()
  File "/usr/local/lib/python3.4/dist-packages/graylog_archiver/graylog_archiver.py", line 28, in archive
    compressed_dir = compress_directory(dump_dir)
  File "/usr/local/lib/python3.4/dist-packages/graylog_archiver/utils.py", line 11, in compress_directory
    invoke.run(cmd, hide=True)
  File "/usr/local/lib/python3.4/dist-packages/invoke/__init__.py", line 38, in run
    return Context().run(command, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/invoke/context.py", line 70, in run
    return runner_class(context=self).run(command, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/invoke/runners.py", line 259, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/invoke/runners.py", line 399, in _run_body
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'tar czvf /data/backups/elasticsearch/graylog_0.tar.gz /data/backups/elasticsearch/graylog_0'

Exit code: 1

Stdout:

/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__6
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__7
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__8
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__9
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__a
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__b
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__c
/data/backups/elasticsearch/graylog_0/indices/graylog_0/meta-snapshot.dat
/data/backups/elasticsearch/graylog_0/meta-snapshot.dat
/data/backups/elasticsearch/graylog_0/snap-snapshot.dat

Stderr:

tar: Removing leading `/' from member names
tar: /data/backups/elasticsearch/graylog_0/indices/graylog_0/1: file changed as we read it
tar: /data/backups/elasticsearch/graylog_0: file changed as we read it

```

But, when I've try to archive by same command in terminal there same error, but tar don't exit:
```
root@graylog:/etc/cron.daily# tar czvf /data/backups/elasticsearch/graylog_0.tar.gz /data/backups/elasticsearch/graylog_0
tar: Removing leading `/' from member names
/data/backups/elasticsearch/graylog_0/
/data/backups/elasticsearch/graylog_0/index
/data/backups/elasticsearch/graylog_0/indices/
/data/backups/elasticsearch/graylog_0/indices/graylog_0/
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/index-0
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/snap-snapshot.dat
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/__0
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/__1
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/__2
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/__3
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/__4
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/__5
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/__6
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/__7
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/__8
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/__9
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/__a
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/__b
/data/backups/elasticsearch/graylog_0/indices/graylog_0/0/__c
tar: /data/backups/elasticsearch/graylog_0/indices/graylog_0/0: file changed as we read it
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/index-0
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/snap-snapshot.dat
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/__0
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/__1
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/__2
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/__3
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/__4
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/__5
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/__6
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/__7
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/__8
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/__9
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/__a
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/__b
/data/backups/elasticsearch/graylog_0/indices/graylog_0/1/__c
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/index-0
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/snap-snapshot.dat
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/__0
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/__1
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/__2
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/__3
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/__4
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/__5
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/__6
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/__7
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/__8
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/__9
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/__a
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/__b
/data/backups/elasticsearch/graylog_0/indices/graylog_0/2/__c
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/index-0
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/snap-snapshot.dat
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__0
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__1
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__2
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__3
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__4
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__5
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__6
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__7
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__8
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__9
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__a
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__b
/data/backups/elasticsearch/graylog_0/indices/graylog_0/3/__c
/data/backups/elasticsearch/graylog_0/indices/graylog_0/meta-snapshot.dat
/data/backups/elasticsearch/graylog_0/meta-snapshot.dat
/data/backups/elasticsearch/graylog_0/snap-snapshot.dat
```

```
root@graylog:/etc/cron.daily# echo $?
0
```

Wait for my pull request to fix this!

**Comment by andrefreitas** [comment]
Closed with your PR, thanks!
